title: Práticas em Bioinformática
description: Materiais didáticos aplicados à toxicologia

url: "https://annejosiele.github.io"
baseurl: "/AJLV-Bioinformatics"

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default